"""second migration

Revision ID: 0617e5b5454b
Revises: 13969ef61760
Create Date: 2023-12-14 14:29:23.031508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0617e5b5454b'
down_revision: Union[str, None] = '13969ef61760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bitpapa_api_tokens',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitpapa_api_tokens_id'), 'bitpapa_api_tokens', ['id'], unique=True)
    op.create_table('price_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_value')
    op.drop_index(op.f('ix_bitpapa_api_tokens_id'), table_name='bitpapa_api_tokens')
    op.drop_table('bitpapa_api_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
