"""empty message

Revision ID: 4fa13e07bcb8
Revises: 06e0f5708df9
Create Date: 2024-01-30 13:25:09.548960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa13e07bcb8'
down_revision: Union[str, None] = '06e0f5708df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bitpapa_api_tokens', sa.Column('is_bot_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitpapa_api_tokens', 'is_bot_active')
    # ### end Alembic commands ###
