"""empty message

Revision ID: 89e0157a6993
Revises: 359fa469d1fb
Create Date: 2024-01-19 15:23:34.879172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e0157a6993'
down_revision: Union[str, None] = '359fa469d1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bitpapa_api_tokens', 'bitpapa_api_tokens', type_='unique')
    op.create_unique_constraint('uq_user_id', 'bitpapa_api_tokens', ['user_id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_user_id', 'bitpapa_api_tokens', type_='unique')
    op.create_unique_constraint('uq_bitpapa_api_tokens', 'bitpapa_api_tokens', ['api_token'])
    # ### end Alembic commands ###
