"""empty message

Revision ID: 91d3aa19df16
Revises: 4fa13e07bcb8
Create Date: 2024-01-30 13:30:06.491461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d3aa19df16'
down_revision: Union[str, None] = '4fa13e07bcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitpapa_api_tokens', 'is_bot_active')
    op.add_column('users', sa.Column('is_bot_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot_active')
    op.add_column('bitpapa_api_tokens', sa.Column('is_bot_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
