"""empty message

Revision ID: 997ed4a8bde4
Revises: b1214375fb6f
Create Date: 2024-02-13 13:29:50.730940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997ed4a8bde4'
down_revision: Union[str, None] = 'b1214375fb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitpapa_user_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_bitpapa_user_name_id'), 'bitpapa_user_name', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitpapa_user_name_id'), table_name='bitpapa_user_name')
    op.drop_table('bitpapa_user_name')
    # ### end Alembic commands ###
