"""empty message

Revision ID: 9c547a802a0f
Revises: d3862684ea34
Create Date: 2024-01-25 14:00:22.092924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c547a802a0f'
down_revision: Union[str, None] = 'd3862684ea34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('erip_sell', sa.Float(), nullable=True),
    sa.Column('erip_buy', sa.Float(), nullable=True),
    sa.Column('card2card_sell', sa.Float(), nullable=True),
    sa.Column('card2card_buy', sa.Float(), nullable=True),
    sa.Column('alfabank_sell', sa.Float(), nullable=True),
    sa.Column('alfabank_buy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('erip_sell_price_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erip_sell_price_value',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='erip_sell_price_value_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='erip_sell_price_value_pkey')
    )
    op.drop_table('price_value')
    # ### end Alembic commands ###
